version: '3.1'
services:
  perl:
    build: .
    volumes:
      - ./:/srv/
    tty: true
    command: bash
    working_dir: /srv
    env_file: .env
    links:
      - v5.6
      - v5.7
      - v8.0
  v5.6:
    image: mysql:5.6
    restart: always
    env_file: .env
  v5.7:
    image: mysql:5.7
    restart: always
    env_file: .env
  v8.0:
    image: mysql:8.0
    restart: always
    env_file: .env
